MB.Presentation.Razor/Areas/Administrator/Pages/ArticleCategoryManagement/List.cshtml.cs
using System.Collections.Generic;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }
        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.List();
        }

        public RedirectToPageResult OnPostDeactivate(int Id)
        {
            _articleCategoryApplication.Deactivate(Id);
            return RedirectToPage("./List");
        }
        public RedirectToPageResult OnPostActivate(int Id)
        { 
            _articleCategoryApplication.Activate(Id);
            return RedirectToPage("./List");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/ArticleManagement/List.cshtml.cs
using System.Collections.Generic;
using MB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.ArticleManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleViewModel> Articles;
        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.List();
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleApplication.Activate(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostDeactivate(long id)
        {
            _articleApplication.Deativate(id);
            return RedirectToPage("./List");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/CommentManagement/List.cshtml.cs
using System.Collections.Generic;
using System.Net.Sockets;
using MB.Application.Contracts.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Razor.Areas.Administrator.Pages.CommentManagement
{
    public class ListModel : PageModel
    {
        private readonly ICommentApplication _commentApplication;
        public List<CommentViewModel> Comments;

        public ListModel(ICommentApplication commentApplication)
        {
            this._commentApplication = commentApplication;
        }

        public void OnGet()
        {
            Comments = _commentApplication.List();
        }

        public RedirectToPageResult OnPostConfirm(long id)
        {
            _commentApplication.Confirm(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostCancel(long id)
        {
            _commentApplication.Cancel(id);
            return RedirectToPage("./List");
        }
    }
}

MB.Presentation.Razor/Areas/Administrator/Pages/CommentManagement/List.cshtml
@page
@using MB.Domain.CommentAgg
@model MB.Presentation.Razor.Areas.Administrator.Pages.CommentManagement.ListModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Commnet List</h3>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Creation Date</th>
                    <th>Status</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td>@comment.Id</td>
                        <td>@comment.Name</td>
                        <td>@comment.Email</td>
                        <td>@comment.Message</td>
                        <td>@comment.CreationDate</td>
                        <td>
                            @if (comment.Status == StatusType.New)
                            {
                                <i class="fa fa-check fa-2x text-success" style="font-size: 36px;color: green"></i>
                            }
                            @if (comment.Status == StatusType.Confirmed)
                            {
                                <i class="fa fa-info fa-2x text-danger" style="font-size: 36px;color: red"></i>
                            }
                            @if (comment.Status == StatusType.Canceled)
                            {
                                <i class="fa fa-close fa-2x text-danger" style="font-size: 36px;color: red"></i>
                            }
                        </td>
                        <td>
                            @if (comment.Status == StatusType.New)
                            {
                                <form method="post" asp-page-handler="Confirm" class="float-left">
                                    <button class="btn btn-success">Confirm</button>
                                    <input type="hidden" name="Id" value="@comment.Id" />
                                </form>

                                <form method="post" asp-page-handler="Cancel" class="float-left">
                                    <button class="btn btn-danger">Cancel</button>
                                    <input type="hidden" name="Id" value="@comment.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>